/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.gabrielwinterusjt.SocialEvents.pages;

import br.com.gabrielwinter.SocialEvents.EventDAO;
import br.com.gabrielwinter.SocialEvents.UserDAO;
import br.com.gabrielwinter.SocialEvents.model.Event;
import br.com.gabrielwinter.SocialEvents.model.User;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Winter
 */
public class NewEventPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public NewEventPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nameForm = new javax.swing.JTextField();
        imgLogo = new javax.swing.JLabel();
        loginTxt = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        descriptionForm = new javax.swing.JTextField();
        loginTxt1 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        finishTxt = new javax.swing.JLabel();
        startForm = new javax.swing.JTextField();
        startTxt = new javax.swing.JLabel();
        finishForm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("FrameLogin\n"); // NOI18N
        setSize(new java.awt.Dimension(500, 500));

        jPanel2.setBackground(new java.awt.Color(253, 166, 27));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));

        nameForm.setBackground(new java.awt.Color(255, 255, 128));
        nameForm.setForeground(new java.awt.Color(253, 166, 27));
        nameForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFormActionPerformed(evt);
            }
        });

        imgLogo.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        imgLogo.setForeground(new java.awt.Color(255, 255, 128));
        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setText("New Event");

        loginTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(255, 255, 128));
        loginTxt.setText("Name");

        cancelBtn.setBackground(new java.awt.Color(255, 255, 128));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(253, 166, 27));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(null);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        descriptionForm.setBackground(new java.awt.Color(255, 255, 128));
        descriptionForm.setForeground(new java.awt.Color(253, 166, 27));
        descriptionForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionFormActionPerformed(evt);
            }
        });

        loginTxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginTxt1.setForeground(new java.awt.Color(255, 255, 128));
        loginTxt1.setText("Description");

        createBtn.setBackground(new java.awt.Color(255, 255, 128));
        createBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createBtn.setForeground(new java.awt.Color(253, 166, 27));
        createBtn.setText("Create");
        createBtn.setBorder(null);
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        finishTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        finishTxt.setForeground(new java.awt.Color(255, 255, 128));
        finishTxt.setText("Finish Date");

        startForm.setBackground(new java.awt.Color(255, 255, 128));
        startForm.setForeground(new java.awt.Color(253, 166, 27));
        startForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFormActionPerformed(evt);
            }
        });

        startTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        startTxt.setForeground(new java.awt.Color(255, 255, 128));
        startTxt.setText("Start Date");

        finishForm.setBackground(new java.awt.Color(255, 255, 128));
        finishForm.setForeground(new java.awt.Color(253, 166, 27));
        finishForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 55, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(237, 237, 237))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(finishForm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(startForm, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameForm, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionForm, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginTxt)
                            .addComponent(loginTxt1)
                            .addComponent(startTxt)
                            .addComponent(finishTxt))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionForm, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishFormActionPerformed

    private void startFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startFormActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:

        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

            final String finishStringDate = this.finishForm.getText();

            final Date finishDate = formatter.parse(finishStringDate);
            java.sql.Date finishSqlDate = new java.sql.Date(finishDate.getTime());

            final String startStringDate = this.startForm.getText();

            final Date startDate = formatter.parse(startStringDate);
            java.sql.Date startSqlDate = new java.sql.Date(startDate.getTime());

            Event event = new Event(
                    this.nameForm.getText(),
                    this.descriptionForm.getText(),
                    finishSqlDate,
                    startSqlDate);

            EventDAO eventDAO = new EventDAO();

            eventDAO.create(event);
        } catch (Exception ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_createBtnActionPerformed

    private void descriptionFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionFormActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);// TODO add your handling code here:

    }//GEN-LAST:event_cancelBtnActionPerformed

    private void nameFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEventPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEventPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField descriptionForm;
    private javax.swing.JTextField finishForm;
    private javax.swing.JLabel finishTxt;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JLabel loginTxt1;
    private javax.swing.JTextField nameForm;
    private javax.swing.JTextField startForm;
    private javax.swing.JLabel startTxt;
    // End of variables declaration//GEN-END:variables
}
