/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.gabrielwinterusjt.mavenproject1.pages;

import br.com.gabrielwinterusjt.mavenproject1.UserDAO;
import br.com.gabrielwinterusjt.mavenproject1.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Winter
 */
public class NewAccountPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public NewAccountPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nameForm = new javax.swing.JTextField();
        imgLogo = new javax.swing.JLabel();
        loginTxt = new javax.swing.JLabel();
        passTxt = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        ageForm = new javax.swing.JTextField();
        loginTxt1 = new javax.swing.JLabel();
        passTxt1 = new javax.swing.JLabel();
        passForm = new javax.swing.JPasswordField();
        createBtn = new javax.swing.JButton();
        loginTxt2 = new javax.swing.JLabel();
        emailForm = new javax.swing.JTextField();
        loginTxt3 = new javax.swing.JLabel();
        genderForm = new javax.swing.JTextField();
        cpfForm = new javax.swing.JTextField();
        loginTxt4 = new javax.swing.JLabel();
        loginForm = new javax.swing.JTextField();
        passTxt2 = new javax.swing.JLabel();
        RepeatPassForm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("FrameLogin\n"); // NOI18N
        setSize(new java.awt.Dimension(500, 500));

        jPanel2.setBackground(new java.awt.Color(253, 166, 27));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));

        nameForm.setBackground(new java.awt.Color(255, 255, 128));
        nameForm.setForeground(new java.awt.Color(253, 166, 27));
        nameForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFormActionPerformed(evt);
            }
        });

        imgLogo.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        imgLogo.setForeground(new java.awt.Color(255, 255, 128));
        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogo.setText("New Account");

        loginTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(255, 255, 128));
        loginTxt.setText("Name");

        passTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passTxt.setForeground(new java.awt.Color(255, 255, 128));
        passTxt.setText("CPF");

        cancelBtn.setBackground(new java.awt.Color(255, 255, 128));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(253, 166, 27));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(null);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        ageForm.setBackground(new java.awt.Color(255, 255, 128));
        ageForm.setForeground(new java.awt.Color(253, 166, 27));
        ageForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFormActionPerformed(evt);
            }
        });

        loginTxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginTxt1.setForeground(new java.awt.Color(255, 255, 128));
        loginTxt1.setText("Age");

        passTxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passTxt1.setForeground(new java.awt.Color(255, 255, 128));
        passTxt1.setText("Password");

        passForm.setBackground(new java.awt.Color(255, 255, 128));
        passForm.setForeground(new java.awt.Color(253, 166, 27));
        passForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFormActionPerformed(evt);
            }
        });

        createBtn.setBackground(new java.awt.Color(255, 255, 128));
        createBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createBtn.setForeground(new java.awt.Color(253, 166, 27));
        createBtn.setText("Create");
        createBtn.setBorder(null);
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        loginTxt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginTxt2.setForeground(new java.awt.Color(255, 255, 128));
        loginTxt2.setText("Gender");

        emailForm.setBackground(new java.awt.Color(255, 255, 128));
        emailForm.setForeground(new java.awt.Color(253, 166, 27));
        emailForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFormActionPerformed(evt);
            }
        });

        loginTxt3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginTxt3.setForeground(new java.awt.Color(255, 255, 128));
        loginTxt3.setText("E-mail");

        genderForm.setBackground(new java.awt.Color(255, 255, 128));
        genderForm.setForeground(new java.awt.Color(253, 166, 27));
        genderForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFormActionPerformed(evt);
            }
        });

        cpfForm.setBackground(new java.awt.Color(255, 255, 128));
        cpfForm.setForeground(new java.awt.Color(253, 166, 27));
        cpfForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFormActionPerformed(evt);
            }
        });

        loginTxt4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginTxt4.setForeground(new java.awt.Color(255, 255, 128));
        loginTxt4.setText("Login");

        loginForm.setBackground(new java.awt.Color(255, 255, 128));
        loginForm.setForeground(new java.awt.Color(253, 166, 27));
        loginForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFormActionPerformed(evt);
            }
        });

        passTxt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passTxt2.setForeground(new java.awt.Color(255, 255, 128));
        passTxt2.setText("Repeat Password");

        RepeatPassForm.setBackground(new java.awt.Color(255, 255, 128));
        RepeatPassForm.setForeground(new java.awt.Color(253, 166, 27));
        RepeatPassForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatPassFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailForm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginTxt3)
                                    .addComponent(nameForm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginTxt)
                                    .addComponent(genderForm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginTxt2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RepeatPassForm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passTxt2)
                                    .addComponent(loginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginTxt4)
                                    .addComponent(passForm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passTxt1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageForm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginTxt1)
                                    .addComponent(passTxt)
                                    .addComponent(cpfForm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 182, Short.MAX_VALUE)
                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loginTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loginTxt4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loginTxt3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(passTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loginTxt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(passTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RepeatPassForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RepeatPassFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatPassFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepeatPassFormActionPerformed

    private void loginFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFormActionPerformed

    private void cpfFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFormActionPerformed

    private void genderFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFormActionPerformed

    private void emailFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFormActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        if (this.passForm.getText().equals(this.RepeatPassForm.getText())) {

            User newUser = new User(false,
                    this.loginForm.getText(),
                    new String(this.passForm.getPassword()),
                    this.nameForm.getText(),
                    Integer.parseInt(this.ageForm.getText()),
                     this.genderForm.getText(),
                     this.emailForm.getText(),
                     this.cpfForm.getText()
            );

            UserDAO userDAO = new UserDAO();
            try {
                userDAO.create(newUser);
                if(userDAO.exist(newUser)){
                    JOptionPane.showMessageDialog(null, "Usuário Criado Com Sucesso");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
            
        }else{
                JOptionPane.showMessageDialog(null, "Usuario nao criado");}


    }//GEN-LAST:event_createBtnActionPerformed

    private void passFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFormActionPerformed

    private void ageFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFormActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void nameFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField RepeatPassForm;
    private javax.swing.JTextField ageForm;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cpfForm;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField emailForm;
    private javax.swing.JTextField genderForm;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField loginForm;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JLabel loginTxt1;
    private javax.swing.JLabel loginTxt2;
    private javax.swing.JLabel loginTxt3;
    private javax.swing.JLabel loginTxt4;
    private javax.swing.JTextField nameForm;
    private javax.swing.JPasswordField passForm;
    private javax.swing.JLabel passTxt;
    private javax.swing.JLabel passTxt1;
    private javax.swing.JLabel passTxt2;
    // End of variables declaration//GEN-END:variables
}
